name: Release .next Folder

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Next.js App
        run: npm run build

      - name: Zip .next Folder
        run: |
          cd out; tar czvf next-build.tar.gz *

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Next.js Build - ${{ github.sha }}
          tag_name: next-build-${{ github.sha }}
          files: next-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
